---

- name: Remove GitLab data directories when recreating data
  when: gitlab_service_volume_recreate | default(false) | bool
  become: true
  ansible.builtin.file:
    path: "{{ gitlab_service_data_dir }}"
    state: absent

- name: Create GitLab data directories
  become: true
  ansible.builtin.file:
    path: "{{ gitlab_service_data_dir }}/{{ item }}"
    state: directory
    owner: "{{ gitlab_service_user }}"
    group: "{{ gitlab_service_user }}"
    mode: "0750"
  loop:
    - config
    - logs
    - data
