---
gitlab_runner_user: gitlab-runner
gitlab_runner_version: "19.2.2"
gitlab_runner_container_method: direct-build
gitlab_runner_direct_build_image: "localhost/gitlab-runner:{{ gitlab_runner_version }}"
gitlab_runner_image_pull_image: "ghcr.io/embtom/gitlab-infra/gitlab-runner:latest"
gitlab_runner_image: >-
  {{ gitlab_runner_direct_build_image
     if gitlab_runner_container_method == 'direct-build'
     else gitlab_runner_image_pull_image }}
gitlab_runner_podman_build_extra_args: >-
  --build-arg GITLAB_RUNNER_VERSION={{ gitlab_runner_version }}

gitlab_runner_force_rebuild: false
gitlab_runner_direct_build_job_image: "localhost/gitlab-runner-image:latest"
gitlab_runner_image_pull_job_image: "ghcr.io/embtom/gitlab-infra/gitlab-runner-image:latest"
gitlab_runner_job_image: >-
  {{ gitlab_runner_direct_build_job_image
     if gitlab_runner_container_method == 'direct-build'
     else gitlab_runner_image_pull_job_image }}
gitlab_runner_job_image_pull_policy:
  - if-not-present
gitlab_runner_job_network: host
gitlab_runner_gitlab_url: "https://{{ gitlab_external_host }}:8081"
gitlab_runner_token: ""
gitlab_runner_name: "{{ ansible_facts['fqdn'] | default(ansible_facts['hostname'], true) }}"
gitlab_runner_request_concurrency: 2
gitlab_runner_service_name: gitlab-runner
gitlab_runner_config_dir: "/var/lib/gitlab-runner/config"
gitlab_runner_builds_dir: "/var/lib/gitlab-runner/builds"
gitlab_runner_ca_dir: "{{ gitlab_runner_config_dir }}/certs"
gitlab_runner_ca_certificate: "{{ gitlab_runner_ca_dir }}/root-ca.crt"
gitlab_runner_ca_container_certificate: /etc/gitlab-runner/certs/root-ca.crt
gitlab_runner_job_ca_certificate: "{{ gitlab_runner_ca_container_certificate }}"
gitlab_runner_podman_socket: >-
  unix:///run/user/{{ gitlab_runner_user_uid }}/podman/podman.sock
gitlab_runner_images:
  - name: "{{ gitlab_runner_image }}"
    context: containers/gitlab-runner
    containerfile: Containerfile
    build_extra_args: "{{ gitlab_runner_podman_build_extra_args }}"
  - name: "{{ gitlab_runner_job_image }}"
    context: containers/gitlab-runner-image
    containerfile: Containerfile.runner
    build_extra_args: ""
gitlab_runner_pull_images:
  - "{{ gitlab_runner_image }}"
  - "{{ gitlab_runner_job_image }}"
